package finalProject;

import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JLabel;

import com.google.gson.Gson;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.net.ssl.HttpsURLConnection;

//
import java.net.HttpURLConnection;
//

//from https://www.javatpoint.com/java-get-current-date
import java.time.format.DateTimeFormatter;
import java.time.LocalDateTime;  
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
//end of code

public class WeatherWindow extends javax.swing.JFrame {
    private WeatherWindow weatherWin;
    private PokemonWindow pokemonWin;
    private ArrayList<JLabel> tempLabelsHigh;
    private ArrayList<JLabel> tempLabelsLow;
    private ArrayList<JLabel> tempLabelsChar;
    private String userLocation;
    private int tempIndex;
    public String weatherIRL;
    
    // from https://mkyong.com/java/how-to-round-double-float-value-to-2-decimal-points-in-java/
    private static final DecimalFormat df = new DecimalFormat("0.00");
    // end of code
    
    public WeatherWindow() {
        initComponents();
        pokemonWin = new PokemonWindow();
        pokemonWin.setWeatherWin(this); //make a method in pokemon frame
        Farenheit.setVisible(false);
        tempLabelsHigh = new ArrayList<JLabel>();
        tempLabelsLow = new ArrayList<JLabel>();
        tempLabelsChar = new ArrayList<JLabel>();

        tempLabelsHigh.add(high1);
        tempLabelsHigh.add(high2);
        tempLabelsHigh.add(high3);
        tempLabelsHigh.add(high4);
        tempLabelsHigh.add(high5);
        tempLabelsHigh.add(high6);
        tempLabelsLow.add(low1);
        tempLabelsLow.add(low2);
        tempLabelsLow.add(low3);
        tempLabelsLow.add(low4);
        tempLabelsLow.add(low5);
        tempLabelsLow.add(low6);
        tempLabelsChar.add(tempChar1);
        tempLabelsChar.add(tempChar2);
        tempLabelsChar.add(tempChar3);
        tempLabelsChar.add(tempChar4);
        tempLabelsChar.add(tempChar5);
        tempLabelsChar.add(tempChar6);
        tempLabelsChar.add(tempChar7);
        tempLabelsChar.add(tempChar8);
        tempLabelsChar.add(tempChar9);
        tempLabelsChar.add(tempChar10);
        tempLabelsChar.add(tempChar11);
        tempLabelsChar.add(tempChar12);
        tempLabelsChar.add(tempChar13);  
        
        //from https://stackoverflow.com/questions/16106605/how-to-delete-text-when-a-user-clicks-a-jtextfield
        cityNameTxt.addMouseListener(new MouseAdapter() { //this clears the txt field upon clicking it
            @Override
            public void mouseClicked(MouseEvent e) {
              cityNameTxt.setText("");
            }
        });
        //end of code
        setImage(weatherImg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        Location = new javax.swing.JLabel();
        Current_Weather = new javax.swing.JLabel();
        Temperature = new javax.swing.JLabel();
        pokeWinBtn = new javax.swing.JButton();
        currentTemp = new javax.swing.JLabel();
        degreeSign = new javax.swing.JLabel();
        Celsius = new javax.swing.JButton();
        Farenheit = new javax.swing.JButton();
        currentWeather = new javax.swing.JLabel();
        currentLocation = new javax.swing.JLabel();
        currentDate = new javax.swing.JLabel();
        //from https://www.javatpoint.com/java-get-current-date
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("HH:mm");
        LocalDateTime now = LocalDateTime.now();
        time = new javax.swing.JLabel();
        day1 = new javax.swing.JLabel();
        low = new javax.swing.JLabel();
        high = new javax.swing.JLabel();
        day = new javax.swing.JLabel();
        day2 = new javax.swing.JLabel();
        day3 = new javax.swing.JLabel();
        day4 = new javax.swing.JLabel();
        day5 = new javax.swing.JLabel();
        day6 = new javax.swing.JLabel();
        high1 = new javax.swing.JLabel();
        high2 = new javax.swing.JLabel();
        high3 = new javax.swing.JLabel();
        high4 = new javax.swing.JLabel();
        high5 = new javax.swing.JLabel();
        high6 = new javax.swing.JLabel();
        low1 = new javax.swing.JLabel();
        low2 = new javax.swing.JLabel();
        low3 = new javax.swing.JLabel();
        low4 = new javax.swing.JLabel();
        low5 = new javax.swing.JLabel();
        low6 = new javax.swing.JLabel();
        degreeSign1 = new javax.swing.JLabel();
        degreeSign2 = new javax.swing.JLabel();
        degreeSign3 = new javax.swing.JLabel();
        degreeSign4 = new javax.swing.JLabel();
        degreeSign5 = new javax.swing.JLabel();
        degreeSign6 = new javax.swing.JLabel();
        degreeSign8 = new javax.swing.JLabel();
        degreeSign9 = new javax.swing.JLabel();
        degreeSign10 = new javax.swing.JLabel();
        degreeSign11 = new javax.swing.JLabel();
        degreeSign12 = new javax.swing.JLabel();
        weatherImg = new javax.swing.JLabel();
        degreeSign13 = new javax.swing.JLabel();
        ChangeLocBtn = new javax.swing.JButton();
        tempChar1 = new javax.swing.JLabel();
        tempChar2 = new javax.swing.JLabel();
        tempChar3 = new javax.swing.JLabel();
        tempChar4 = new javax.swing.JLabel();
        tempChar5 = new javax.swing.JLabel();
        tempChar6 = new javax.swing.JLabel();
        tempChar7 = new javax.swing.JLabel();
        tempChar8 = new javax.swing.JLabel();
        tempChar9 = new javax.swing.JLabel();
        tempChar10 = new javax.swing.JLabel();
        tempChar11 = new javax.swing.JLabel();
        tempChar12 = new javax.swing.JLabel();
        tempChar13 = new javax.swing.JLabel();
        cityNameTxt = new javax.swing.JTextField();
        stateLabel = new javax.swing.JLabel();

        jLabel9.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Weather");
        setBackground(new java.awt.Color(51, 51, 255));

        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Weathermon.png"))); // NOI18N

        Time.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Time.png"))); // NOI18N
        Time.setText(":");

        Date.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Date.png"))); // NOI18N
        Date.setText(":");

        Location.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Location.png"))); // NOI18N
        Location.setText(":");

        Current_Weather.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Current-Weather.png"))); // NOI18N
        Current_Weather.setText(":");

        Temperature.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Temperature.png"))); // NOI18N
        Temperature.setText(":");

        pokeWinBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokmon.png"))); // NOI18N
        pokeWinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pokeWinBtnActionPerformed(evt);
            }
        });

        currentTemp.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        currentTemp.setText(setCurrentTemp());

        degreeSign.setText("º");

        Celsius.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Celsius.png"))); // NOI18N
        Celsius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CelsiusActionPerformed(evt);
            }
        });

        Farenheit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Farenheit.png"))); // NOI18N
        Farenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FarenheitActionPerformed(evt);
            }
        });

        currentWeather.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        currentWeather.setText(getResponse(getLocationResp("beverly")[0].getLat(),getLocationResp("beverly")[0].getLon()).getList()[0].getWeather()[0].getDescription());

        currentLocation.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        currentLocation.setText(getResponse(getLocationResp("beverly")[0].getLat(), getLocationResp("beverly")[0].getLon()).getCity().getName());

        currentDate.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        currentDate.setText(setDate(0)[0]);

        time.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        time.setText(dtf.format(now));
        //end of code

        day1.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        day1.setText(setDate(0)[0]);

        low.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Low.png"))); // NOI18N

        high.setIcon(new javax.swing.ImageIcon(getClass().getResource("/High.png"))); // NOI18N

        day.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Day.png"))); // NOI18N
        day.setText(":");

        day2.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        day2.setText(setDate(7)[0]);

        day3.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        day3.setText(setDate(15)[0]);

        day4.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        day4.setText(setDate(23)[0]);

        day5.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        day5.setText(setDate(31)[0]);

        day6.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        day6.setText(setDate(39)[0]);

        high1.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        high1.setText(setCurrentTempHigh(0));

        high2.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        high2.setText(setCurrentTempHigh(7));

        high3.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        high3.setText(setCurrentTempHigh(15));

        high4.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        high4.setText(setCurrentTempHigh(23));

        high5.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        high5.setText(setCurrentTempHigh(31));

        high6.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        high6.setText(setCurrentTempHigh(39));

        low1.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        low1.setText(setCurrentTempLow(0));

        low2.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        low2.setText(setCurrentTempLow(7));

        low3.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        low3.setText(setCurrentTempLow(15));

        low4.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        low4.setText(setCurrentTempLow(23));

        low5.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        low5.setText(setCurrentTempLow(31));

        low6.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        low6.setText(setCurrentTempLow(39));

        degreeSign1.setText("º");

        degreeSign2.setText("º");

        degreeSign3.setText("º");

        degreeSign4.setText("º");

        degreeSign5.setText("º");

        degreeSign6.setText("º");

        degreeSign8.setText("º");

        degreeSign9.setText("º");

        degreeSign10.setText("º");

        degreeSign11.setText("º");

        degreeSign12.setText("º");

        degreeSign13.setText("º");

        ChangeLocBtn.setText("Change Location");
        ChangeLocBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeLocBtnActionPerformed(evt);
            }
        });

        tempChar1.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        tempChar1.setText("F");

        tempChar2.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        tempChar2.setText("F");

        tempChar3.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        tempChar3.setText("F");

        tempChar4.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        tempChar4.setText("F");

        tempChar5.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        tempChar5.setText("F");

        tempChar6.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        tempChar6.setText("F");

        tempChar7.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        tempChar7.setText("F");

        tempChar8.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        tempChar8.setText("F");

        tempChar9.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        tempChar9.setText("F");

        tempChar10.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        tempChar10.setText("F");

        tempChar11.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        tempChar11.setText("F");

        tempChar12.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        tempChar12.setText("F");

        tempChar13.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        tempChar13.setText("F");

        cityNameTxt.setText("Enter City Name");

        stateLabel.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        stateLabel.setText(getLocationResp("Beverly")[0].getState()
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pokeWinBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(544, 544, 544)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(high4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(degreeSign4, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tempChar8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(low4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(degreeSign8, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tempChar9))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Time)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(time))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Location)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(currentLocation)
                        .addGap(18, 18, 18)
                        .addComponent(stateLabel)
                        .addGap(18, 18, 18)
                        .addComponent(ChangeLocBtn)
                        .addGap(18, 18, 18)
                        .addComponent(cityNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Date)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(currentDate))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Current_Weather)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(currentWeather))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Temperature)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(currentTemp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(degreeSign, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tempChar1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Celsius)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Farenheit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(day)
                            .addComponent(high))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(day1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(low1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(degreeSign12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tempChar4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(high1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(degreeSign1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tempChar2))))))
                    .addComponent(low))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(low2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(degreeSign2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tempChar5))
                    .addComponent(day2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(high2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(degreeSign10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tempChar3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(day3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(high3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(degreeSign3, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tempChar6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(low3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(degreeSign9, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tempChar7)))
                        .addGap(18, 18, 18)
                        .addComponent(day4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(day5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(high5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(degreeSign5, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tempChar10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(low5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(degreeSign13, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tempChar11)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(low6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(degreeSign11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tempChar13)
                                        .addContainerGap(12, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(high6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(degreeSign6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tempChar12))
                                            .addComponent(day6, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(weatherImg, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Time)
                    .addComponent(time))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Date)
                            .addComponent(currentDate))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Location)
                                .addComponent(currentLocation))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ChangeLocBtn)
                                .addComponent(cityNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(stateLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Current_Weather)
                            .addComponent(currentWeather))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Temperature)
                            .addComponent(currentTemp)
                            .addComponent(degreeSign)
                            .addComponent(tempChar1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Farenheit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Celsius))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                        .addComponent(weatherImg)
                        .addGap(31, 31, 31)))
                .addComponent(pokeWinBtn)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(low1)
                        .addComponent(degreeSign12)
                        .addComponent(tempChar4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(day)
                            .addComponent(day1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(day2)
                            .addComponent(day3)
                            .addComponent(day4)
                            .addComponent(day5)
                            .addComponent(day6))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(high1)
                                        .addComponent(degreeSign1)
                                        .addComponent(high2)
                                        .addComponent(degreeSign10)
                                        .addComponent(high3)
                                        .addComponent(degreeSign3)
                                        .addComponent(high4)
                                        .addComponent(degreeSign4)
                                        .addComponent(tempChar2)
                                        .addComponent(tempChar3)
                                        .addComponent(tempChar6)
                                        .addComponent(tempChar8)
                                        .addComponent(high5)
                                        .addComponent(degreeSign5)
                                        .addComponent(tempChar10)
                                        .addComponent(high6)
                                        .addComponent(degreeSign6)
                                        .addComponent(tempChar12))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(high)
                                        .addGap(34, 34, 34)
                                        .addComponent(low))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(degreeSign9)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(low3)
                                        .addComponent(low2)
                                        .addComponent(degreeSign2)
                                        .addComponent(tempChar5))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(low4)
                                        .addComponent(degreeSign8)
                                        .addComponent(tempChar7)
                                        .addComponent(tempChar9)
                                        .addComponent(low5)
                                        .addComponent(degreeSign13)
                                        .addComponent(tempChar11)
                                        .addComponent(low6)
                                        .addComponent(degreeSign11)
                                        .addComponent(tempChar13)))))))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    public String setCurrentTemp(){
        String temp = (df.format(1.8 * ((getResponse(getLocationResp("beverly")[0].getLat(),getLocationResp("beverly")[0].getLon()).getList()[0].getMain().getTemp()) - 273) + 32) + "");
        return temp;
    }
    
    public String setCurrentTempHigh(int indexNum){
        String highTemp = (df.format(1.8 * ((getResponse(getLocationResp("beverly")[0].getLat(),getLocationResp("beverly")[0].getLon()).getList()[indexNum].getMain().getTemp_max()) - 273) + 32) + "");
        return highTemp;
    }
    
    public String setCurrentTempLow(int indexNum){
        String lowTemp = (df.format(1.8 * ((getResponse(getLocationResp("beverly")[0].getLat(),getLocationResp("beverly")[0].getLon()).getList()[indexNum].getMain().getTemp_min()) - 273) + 32) + "");
        return lowTemp;
    }
    
    public String[] setDate(int indexNum) {
        String dateNum = getResponse(getLocationResp("beverly")[0].getLat(),getLocationResp("beverly")[0].getLon()).getList()[indexNum].getDt_Text(); 
        String[] date_arr = dateNum.split(" ");
        return date_arr;
    }
    
    public String setNewLocTempHigh(String city, int tempIndex){
        String tempHigh = (df.format(1.8 * ((getResponse(getLocationResp(city)[0].getLat(),getLocationResp(city)[0].getLon()).getList()[tempIndex].getMain().getTemp_max()) - 273) + 32) + "");
        return tempHigh;
    }
    
    public String setNewLocTempLow(String city, int tempIndex){
        String tempLow = (df.format(1.8 * ((getResponse(getLocationResp(city)[0].getLat(),getLocationResp(city)[0].getLon()).getList()[tempIndex].getMain().getTemp_min()) - 273) + 32) + "");
        return tempLow;
    }
    
    public String setNewLocCity(String userLocation){
        String city = getResponse(getLocationResp(userLocation)[0]
                .getLat(), getLocationResp(userLocation)[0].getLon()).getCity()
                .getName();
        return city;
    }
    
    public String setNewLocState(String userLocation){
        String state = getLocationResp(userLocation)[0].getState();
        return state;
    }
    
    public String setNewLocWeather(String userLocation){
        String weather = getResponse(getLocationResp(userLocation)[0]
                .getLat(),getLocationResp(userLocation)[0].getLon()).getList()
                [0].getWeather()[0].getDescription();
        return weather;
    }
    
    public String setNewLocTemp(String userLocation){
        String temp = df.format(1.8 * ((getResponse(getLocationResp(userLocation)
                [0].getLat(),getLocationResp(userLocation)[0].getLon()).getList()[0]
                .getMain().getTemp()) - 273) + 32) + "";
        return temp;
    }
    
    public void setImage(JLabel label_to_change){ //changes the img based on the current weather
        String currentWeather1 = getCurrentWeather();
        if (currentWeather1.contains("clear") || currentWeather1.contains("sun")){
            label_to_change.setIcon(new ImageIcon("src/main/resources/sun.png"));
        }
        if (currentWeather1.contains("cloud") || currentWeather1.contains("part")){
            label_to_change.setIcon(new ImageIcon("src/main/resources/cloud.png"));
        }
        if (currentWeather1.contains("rain")){
            label_to_change.setIcon(new ImageIcon("src/main/resources/rain.png"));
        }
        if (currentWeather1.contains("wind")){
            label_to_change.setIcon(new ImageIcon("src/main/resources/wind.png"));
        }
        if (currentWeather1.contains("thunder") || currentWeather1.contains("storm") || currentWeather1.contains("lightening")){
            label_to_change.setIcon(new ImageIcon("src/main/resources/thunder.png"));
        }
        if (currentWeather1.contains("snow")){
            label_to_change.setIcon(new ImageIcon("src/main/resources/snow.png"));
        }
    }
    
    public String getCurrentWeather(){
        weatherIRL = currentWeather.getText();
        return weatherIRL;
    }
    
    public String getCityLocation(){
        String location = currentLocation.getText();
        return location;
    }
    
    public String getStateLocation(){
        String location = stateLabel.getText();
        return location;
    }
    
    //returns a location response from open weather map getting the lat and lon of the city the user put in
    public static Location[] getLocationResp(String city_name){
        Gson gson = new Gson();
        try {
            URL url = new URL("http://api.openweathermap.org/geo/1.0/direct?q=" 
                    + city_name + "&limit=5&appid=cbd0dd1ec0267431ba7bdb41a4f8051e");
            HttpURLConnection connection = (HttpURLConnection)url.openConnection();
            BufferedReader in = new BufferedReader(
                        new InputStreamReader(connection.getInputStream()));
            String tmp = in.readLine();
            Location[] location_resp = gson.fromJson(tmp, Location[].class);
            return location_resp;
        } catch (MalformedURLException ex) {
            Logger.getLogger(City.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(City.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    //returns weather information from open weather map to the application
    public static Response getResponse(double lat, double lon){
        Gson gson = new Gson();
        try {
            URL url = new URL("https://api.openweathermap.org/data/2.5/forecast?lat=" + lat + 
                    "&lon=" + lon + "&appid=cbd0dd1ec0267431ba7bdb41a4f8051e");
            HttpsURLConnection conn = (HttpsURLConnection)url.openConnection();
            BufferedReader in = new BufferedReader(
                        new InputStreamReader(conn.getInputStream()));
            String tmp = in.readLine();
            Response gen_resp = gson.fromJson(tmp, Response.class);
            return gen_resp;
        } catch (MalformedURLException ex) {
            Logger.getLogger(City.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(City.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    private void pokeWinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pokeWinBtnActionPerformed
        pokemonWin.setVisible(true); //changes the main window to pokemon window
        this.setVisible(false);
    }//GEN-LAST:event_pokeWinBtnActionPerformed

    private void CelsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CelsiusActionPerformed
        for(int i = 0; i<tempLabelsHigh.size(); i++){ //changes the temp label from
            //farenheit to celsius
            JLabel tmpHigh = tempLabelsHigh.get(i);
            JLabel tmpLow = tempLabelsLow.get(i);
            String tmpLabelHigh = tmpHigh.getText();
            String tmpLabelLow = tmpLow.getText();            
            Double fTempHigh = Double.parseDouble(tmpLabelHigh);
            Double fTempLow = Double.parseDouble(tmpLabelLow);           
            Double cTempHigh = fTempHigh / 32.0;
            Double cTempLow = fTempLow / 32.0;
            if(Celsius.isEnabled()){
                tmpHigh.setText(df.format(cTempHigh) + "");
                tmpLow.setText(df.format(cTempLow) + "");
            }
        }
            String tmpGen = currentTemp.getText();
            Double fTemp = Double.parseDouble(tmpGen);
            Double cTemp = fTemp / 32.0;
            if(Celsius.isEnabled()){
                currentTemp.setText(df.format(cTemp) + "");
        }
        for (int i=0;i<tempLabelsChar.size();i++){
            JLabel tmpChar = tempLabelsChar.get(i);
            tmpChar.setText("C");
        }
        //Visibility of button after clicking Celsius
        Celsius.setVisible(false);
        Farenheit.setVisible(true);
    }//GEN-LAST:event_CelsiusActionPerformed

    private void FarenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FarenheitActionPerformed
        for (int i = 0; i<tempLabelsHigh.size(); i++) { //changes the temperature
            //from Celsius to farentheit
            
            JLabel tmpHigh = tempLabelsHigh.get(i);
            JLabel tmpLow = tempLabelsLow.get(i);
            String tmpLabelHigh = tmpHigh.getText();
            String tmpLabelLow = tmpLow.getText();            
            Double cTempHigh = Double.parseDouble(tmpLabelHigh);
            Double cTempLow = Double.parseDouble(tmpLabelLow);
            Double fTempHigh = cTempHigh * 32.0;
            Double fTempLow = cTempLow * 32.0;

            if(Farenheit.isEnabled()){
                tmpHigh.setText(df.format(fTempHigh) + "");
                tmpLow.setText(df.format(fTempLow) + "");
            }
        }
            String tmpGen = currentTemp.getText();
            Double cTemp = Double.parseDouble(tmpGen);
            Double fTemp = cTemp * 32.0;
            if(Farenheit.isEnabled()){
                currentTemp.setText(df.format(fTemp) + "");
            }
            for (int i=0;i<tempLabelsChar.size();i++){
                JLabel tmpChar = tempLabelsChar.get(i);
                tmpChar.setText("F");
            }
            //Visibilty of button after clicking Farenheit
            Celsius.setVisible(true);
            Farenheit.setVisible(false);
    }//GEN-LAST:event_FarenheitActionPerformed

    private void ChangeLocBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeLocBtnActionPerformed
        userLocation = cityNameTxt.getText();
        try {
            for (int i=0; i<tempLabelsHigh.size(); i++){
                JLabel tmpChangeHigh = tempLabelsHigh.get(i);
                JLabel tmpChangeLow = tempLabelsLow.get(i);
                if (i != 0) {
                    tempIndex = (i * 8) - 1;
                } else { 
                    tempIndex = 0;
                }
        tmpChangeHigh.setText(setNewLocTempHigh(userLocation, tempIndex));
        tmpChangeLow.setText(setNewLocTempLow(userLocation, tempIndex));
        }
        currentLocation.setText(setNewLocCity(userLocation));
        currentWeather.setText(setNewLocWeather(userLocation));
        currentTemp.setText(setNewLocTemp(userLocation));
        stateLabel.setText(setNewLocState(userLocation));
        
        } catch (java.lang.NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Please Enter a Valid City Name");
        } catch (java.lang.ArrayIndexOutOfBoundsException ex) {
            JOptionPane.showMessageDialog(null, "Please Enter a Valid City Name");
        } catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Please Enter a Valid City Name");
        } 
        
        pokemonWin.updateContents(getCurrentWeather(), getCityLocation(), getStateLocation());
        setImage(weatherImg);
    }//GEN-LAST:event_ChangeLocBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        WeatherWindow weatherWin = new WeatherWindow();
        weatherWin.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Celsius;
    public javax.swing.JButton ChangeLocBtn;
    private javax.swing.JLabel Current_Weather;
    private javax.swing.JLabel Date;
    private javax.swing.JButton Farenheit;
    private javax.swing.JLabel Location;
    private javax.swing.JLabel Temperature;
    private javax.swing.JLabel Time;
    private javax.swing.JTextField cityNameTxt;
    private javax.swing.JLabel currentDate;
    private javax.swing.JLabel currentLocation;
    private javax.swing.JLabel currentTemp;
    private javax.swing.JLabel currentWeather;
    private javax.swing.JLabel day;
    private javax.swing.JLabel day1;
    private javax.swing.JLabel day2;
    private javax.swing.JLabel day3;
    private javax.swing.JLabel day4;
    private javax.swing.JLabel day5;
    private javax.swing.JLabel day6;
    private javax.swing.JLabel degreeSign;
    private javax.swing.JLabel degreeSign1;
    private javax.swing.JLabel degreeSign10;
    private javax.swing.JLabel degreeSign11;
    private javax.swing.JLabel degreeSign12;
    private javax.swing.JLabel degreeSign13;
    private javax.swing.JLabel degreeSign2;
    private javax.swing.JLabel degreeSign3;
    private javax.swing.JLabel degreeSign4;
    private javax.swing.JLabel degreeSign5;
    private javax.swing.JLabel degreeSign6;
    private javax.swing.JLabel degreeSign8;
    private javax.swing.JLabel degreeSign9;
    private javax.swing.JLabel high;
    private javax.swing.JLabel high1;
    private javax.swing.JLabel high2;
    private javax.swing.JLabel high3;
    private javax.swing.JLabel high4;
    private javax.swing.JLabel high5;
    private javax.swing.JLabel high6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel low;
    private javax.swing.JLabel low1;
    private javax.swing.JLabel low2;
    private javax.swing.JLabel low3;
    private javax.swing.JLabel low4;
    private javax.swing.JLabel low5;
    private javax.swing.JLabel low6;
    private javax.swing.JButton pokeWinBtn;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JLabel tempChar1;
    private javax.swing.JLabel tempChar10;
    private javax.swing.JLabel tempChar11;
    private javax.swing.JLabel tempChar12;
    private javax.swing.JLabel tempChar13;
    private javax.swing.JLabel tempChar2;
    private javax.swing.JLabel tempChar3;
    private javax.swing.JLabel tempChar4;
    private javax.swing.JLabel tempChar5;
    private javax.swing.JLabel tempChar6;
    private javax.swing.JLabel tempChar7;
    private javax.swing.JLabel tempChar8;
    private javax.swing.JLabel tempChar9;
    private javax.swing.JLabel time;
    private javax.swing.JLabel title;
    private javax.swing.JLabel weatherImg;
    // End of variables declaration//GEN-END:variables
}
